name: employer_engagement_env
dependencies:
  - python=3.10.0
  - scikit-learn
  - numpy
  - shap
  - xgboost
  - pip:
    - azureml-defaults
    - azureml-pipeline
    - azureml-widgets
    - pandas
    - sklearn
    - pyarrow
    - joblib
    - python==3.10.0