name: employer_engagement_env
dependencies:
  - python=3.7.10
  - scikit-learn
  - numpy
  - shap
  - xgboost=1.4.2
  - pip:
    - azureml-defaults
    - azureml-pipeline
    - azureml-widgets
    - pandas
    - sklearn
    - pyarrow
    - joblib
