trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- group: RELEASE das-data-management-ai
- group: RELEASE Management Resources
- name: Deploy
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]

pool:
  name: DAS - Continuous Deployment Agents
  workspace:
    clean: all

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.26
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.5.9
    endpoint: SkillsFundingAgency
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest


stages:
## Add linting and unit tests

- stage: BuildAndTrainAT
  displayName: Build and Train AT
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy-pipeline.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: BuildAndTrainTest
  displayName: Build and Train Test
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy-pipeline.yml
    parameters:
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: BuildAndTrainPP
  displayName: Build and Train PreProd
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: PreProd Management Resources
  - group: PreProd DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy-pipeline.yml
    parameters:
      Environment: PP
      ServiceConnection: SFA-DIG-PreProd-ARM
