parameters:
  Environment:
  ServiceConnection:

jobs:
  - deployment: DeployInfra
    environment: ${{ parameters.Environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
              parameters:
                ServiceConnection: ${{ parameters.ServiceConnection }}
                SubscriptionId: $(SubscriptionId)
                Location: $(ResourceGroupLocation)
                Environment: ${{ parameters.Environment }}
                TemplatePath: azure/template.json
                ParametersPath: azure/template.parameters.json
                IsMultiRepoCheckout: true
  - job: BuildAndTrain
    dependsOn: DeployInfra
    variables:
      - name: WorkspaceName
        value: $[ dependencies.DeployInfra.outputs['ARMOutput.WorkspaceName.value'] ]
      - name: ResourceGroupName
        value: $[ dependencies.DeployInfra.outputs['ARMOutput.ResourceGroupName.value'] ]
      - name: ComputeName
        value: $[ dependencies.DeployInfra.outputs['ARMOutput.ComputeName.value'] ]
    steps:
      - checkout: self
      - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

      ## Run some tests
      - task: AzureCLI@2
        displayName: "Install AML CLI"
        inputs:
          azureSubscription: ${{ parameters.ServiceConnection }}
          scriptLocation: inlineScript
          scriptType: "bash"
          inlineScript: "az extension add -n azure-cli-ml"

      - task: AzureCLI@2
        displayName: "Attach folder to workspace"
        inputs:
          azureSubscription: ${{ parameters.ServiceConnection }}
          workingDirectory: models/placeholder
          scriptLocation: inlineScript
          scriptType: "bash"
          inlineScript: "az ml folder attach --workspace-name $(WorkspaceName) --resource-group $(WorkspaceName)"

      - task: AzureCLI@2
        displayName: "Train model"
        inputs:
          azureSubscription: ${{ parameters.ServiceConnection }}
          workingDirectory: models/placeholder
          scriptLocation: inlineScript
          scriptType: "bash"
          inlineScript: "az ml run submit-script --run-configuration-name config/train --target $(ComputeName) --experiment-name placeholder-exp --output-metadata-file run.json train.py"

      ## Validate output before registering?

      - task: AzureCLI@2
        displayName: 'Register model'
        inputs:
          azureSubscription: ${{ parameters.ServiceConnection }}
          workingDirectory: models/placeholder
          scriptLocation: inlineScript
          scriptType: 'bash'
          inlineScript: 'az ml model register --name placeholder-model --run-metadata-file run.json --asset-path outputs/output.pkl --output-metadata-file model.json'

