jobs:
- job: CodeBuild
  variables:
  - group: BUILD Management Resources
  steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

    - task: CopyFiles@2
      displayName: Copy Files to $(build.artifactstagingdirectory)/publish
      inputs:
        Contents: |
          azure/**
        TargetFolder: $(build.artifactstagingdirectory)/publish
        OverWrite: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifact drop
      inputs:
        targetPath: $(build.artifactstagingdirectory)/publish
        artifactName: drop
