parameters:
  Environment:
  ServiceConnection:

jobs:
- deployment: DeployInfra
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            Location: $(ResourceGroupLocation)
            Environment: ${{ parameters.Environment }}
            TemplatePath: das-data-management-ai/azure/template.json
            ParametersPath: das-data-management-ai/azure/template.parameters.json
            IsMultiRepoCheckout: true
- job: DeployPipelines
  dependsOn: DeployInfra
  pool:
    vmImage: ubuntu-latest
  container: mlops
  variables:
  - name: WorkspaceName
    value: $[ dependencies.DeployInfra.outputs['DeployInfra.ArmOutputs${{ parameters.Environment }}.WorkspaceName'] ]
  - name: ResourceGroupName
    value: $[ dependencies.DeployInfra.outputs['DeployInfra.ArmOutputs${{ parameters.Environment }}.ResourceGroupName'] ]
  - name: ComputeName
    value: $[ dependencies.DeployInfra.outputs['DeployInfra.ArmOutputs${{ parameters.Environment }}.ComputeName'] ]
  steps:
  - checkout: self
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: ${{ parameters.ServiceConnection }}
      scriptType: filePath
      scriptPath: $(Build.SourcesDirectory)/azure/New-MLConfigFile.ps1
      scriptArguments:
        -ResourceGroupName $(WorkspaceName) `
        -WorkspaceName $(WorkspaceName)
      azurePowerShellVersion: latestVersion
      pwsh: true
  - task: AzureCLI@2
    displayName: "Deploy ML pipelines"
    inputs:
      azureSubscription: ${{ parameters.ServiceConnection }}
      workingDirectory: $(Build.SourcesDirectory)
      scriptLocation: inlineScript
      scriptType: "pscore"
      failOnStandardError: true
      inlineScript: |
        python -m ml_service.pipelines.employer_engagement_build_pipeline