name: TestENVAZ
channels:
  - defaults
dependencies:
  - python==3.7.10
  - xgboost
  - shap
  - scikit-learn
  - pip
  - pip:
    - azureml-core
    - azureml-pipeline
    - azureml-widgets
    - pandas
    - scikit-learn
    - pyarrow
    - joblib
    - matplotlib
