name: employer_engagement_env
dependencies:
  - python=3.7.10
  - scikit-learn
  - numpy
  - shap
  - xgboost
  - pip:
    - azureml-defaults
    - azureml-pipeline
    - azureml-widgets
    - pandas
    - pyarrow
    - joblib
    - matplotlib
    - tensorflow
    - MIDASpy
